/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package part2;

import java.util.Random;

public class RandAccess {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Random rand = new Random();
		rand.nextInt(9);
		boolean loop = true;
		int tries = 0;
		while(loop) {


			int input = rand.nextInt(10);
			tries++;
			if (input == 9) {
				
				input = rand.nextInt(10);
				tries++;
				
				if (input == 9) {
					input = rand.nextInt(10);
					tries++;
					if (input == 7) {
						input = rand.nextInt(10);
						tries++;
						if (input == 0) {
							input = rand.nextInt(10);
							tries++;
							if (input == 6) {
								input = rand.nextInt(10);
								tries++;
								if (input == 1) {
									System.out.println("Unlocked");
									loop = false;
								}else if (input == 4){
									System.out.println("Locked");
									tries++;
								}
							}
						}
					}
				}
			}
			
			
			
			
			
		}
		
		System.out.println(tries);

	}

}
