/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs330;

import java.util.InputMismatchException;
import java.util.Scanner;

public class AccessCode {
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		
		System.out.print("Enter Access Code:");
		boolean loop = true;
		while(loop) {
			try {
				lockkey();
				loop = false;
			}catch(InputMismatchException s) {
				
				;
			}
		}
		
			
			
			
		}
	
	public static void lockkey() {
		Scanner scan = new Scanner(System.in);
		while(true) {

			int input = scan.nextInt();
			if (input == 9) {
				input = scan.nextInt();
				if (input == 9) {
					input = scan.nextInt();
					if (input == 7) {
						input = scan.nextInt();
						if (input == 0) {
							input = scan.nextInt();
							if (input == 6) {
								input = scan.nextInt();
								if (input == 1) {
									System.out.println("Unlocked");
								}else if (input == 4){
									System.out.println("Locked");
								}
							}
						}
					}
				}
			}
			
			
			
			
			}
	}
}